{
    "name": "AWTAD PARKING",
    "version": "18.0.1.0.0",
    "summary": "Manage tenant access cards and parking permits for Al-Majdoul Tower",
    "category": "Operations",
    "author": "AWTAD",
    "license": "LGPL-3",
    "depends": ["base", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/client_views.xml",
        "views/unit_views.xml",
        "views/client_role_views.xml",
        "views/access_card_views.xml",
        "views/parking_views.xml",
        "views/state_log_views.xml",
        "views/report_views.xml",
        "views/res_users_views.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
}
